### ISSUE TITLE
Wrong version in README: 1.5 instead of 1.4

### ISSUE THREAD

**Issue by vitalijr2** [kennycason/soroban#6]
Maven Central has last version 1.4.

As far as I understand from sources the last production version is 1.4 too: no any great changes after update pom.xml to 1.5. Looks like 1.5 should be 1.5-SNAPSHOT.

But in README are next lines:

    <dependency>
        <groupId>com.kennycason</groupId>
        <artifactId>soroban</artifactId>
        <version>1.5</version>
    </dependency>

**Comment by kennycason** [comment]
@ur6lad good catch! Thanks, fixed.

Also, as I coded this as a side project for fun, please let me know if you find any problems :)

I'll later consider update the version in code base to -SNAPSHOT, but may unless this project becomes more popular. I did update the README however.
